package com.zzb.cif;

import java.util.HashMap;
import java.util.Map;

import com.alibaba.fastjson.JSONObject;
import com.cninsure.core.tools.util.ValidateUtil;
import com.common.HttpClientUtil;

public class WorkAddPoll {
	public static void main(String[] args) {
		Map<String, String> params = new HashMap<String, String>();
//		{"processinstanceid":391260,"data":{"issecond":"0"},"taskName":"支付","userid":"admin"}
//		 params.put("datas", "{\"processinstanceid\":329335,\"data\":{\"result\":\"1\",\"skipSpirit\":\"1\"},\"taskName\":\"精灵核保\",\"userid\":\"admin\"}");
//		params.put("datas", "{\"processinstanceid\":391260,\"data\":{\"issecond\":\"0\"},\"taskName\":\"支付\",\"userid\":\"admin\"}")
		//EDI承保
//		params.put("datas","{\"processinstanceid\":316211,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵承保\",\"userid\":\"admin\"}");
//		params.put("datas","{\"processinstanceid\":326920,\"data\":{\"result\":\"1\",\"skipSpirit\":\"1\"},\"taskName\":\"精灵核保\",\"userid\":\"admin\"}");
//		String result = HttpClientUtil.doGet("http://119.29.37.183:8080/workflow//process/completeSubTask",params);
//		HttpClientUtil.doGet("http://115.159.235.13:9080/workflow/process/completeTask",params);
		
//		String[] a ={
//				"{\"processinstanceid\":2008317,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008251,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008595,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008320,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006637,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005818,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008069,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009676,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008602,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009303,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008333,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009308,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008607,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008267,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006905,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007083,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007089,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007896,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007682,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009238,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008623,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008621,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009257,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006663,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005838,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006395,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007698,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006923,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006072,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006075,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009693,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006673,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007389,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006506,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008637,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006938,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007110,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009811,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009701,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009099,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009581,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009276,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005625,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008103,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008291,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008109,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005629,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008119,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006099,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006100,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008293,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008123,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009586,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005639,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006699,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009703,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009285,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006521,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005887,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008136,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007120,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006113,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006113,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006523,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009706,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005233,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006958,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009121,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006338,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006532,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007332,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007333,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007728,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009298,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007956,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009337,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009336,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009335,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008833,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007957,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006336,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008833,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008836,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007730,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007531,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005903,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006731,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007731,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008383,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006968,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006970,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006358,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006353,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009723,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008385,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007739,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009313,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009133,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009315,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006733,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007351,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006979,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006981,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008678,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005259,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005261,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007138,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008393,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006371,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005683,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005683,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006137,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009973,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009978,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009982,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009981,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005327,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009735,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006986,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008687,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006989,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009325,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005933,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005931,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009613,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006750,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005933,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009168,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009166,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009169,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008870,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008868,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006996,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009989,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006172,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006386,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006760,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2003821,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006388,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006178,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008888,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007377,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009379,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007163,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006571,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009185,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007989,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009997,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009628,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006578,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008180,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009383,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008333,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008337,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007570,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007576,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008535,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008538,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008537,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009387,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008353,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005961,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007018,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005385,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007302,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005726,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009395,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006209,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006792,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007592,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008186,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007597,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008927,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006217,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007599,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007601,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007600,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009871,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007800,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009503,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006805,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2010011,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008553,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008555,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007315,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005736,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005516,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005518,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005521,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009363,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006320,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006321,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008373,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005755,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005992,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005989,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005990,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009883,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007207,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006230,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008013,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008018,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007816,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006827,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006603,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006830,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009763,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008957,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008213,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008380,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008383,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008382,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005535,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005536,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007213,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006830,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006831,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007050,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2003072,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006253,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009220,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009381,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006009,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006010,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007832,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008752,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009526,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008753,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005551,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005789,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009529,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009530,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006259,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007339,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006263,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008399,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008031,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008239,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2010035,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008578,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007636,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005563,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008987,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008988,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005797,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007071,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007658,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008586,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006032,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007073,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008998,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009913,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008769,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}"
//		};
//		String a[] ={
//				"{\"processinstanceid\":2009002,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008418,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009915,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007244,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009007,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006892,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006893,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007083,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008782,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009403,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009561,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008606,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008265,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009410,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006483,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009569,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005597,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009413,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007095,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006487,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006491,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009251,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008079,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008445,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009073,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009690,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009692,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009789,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005852,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005853,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009265,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007273,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009079,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006499,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007103,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006932,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007487,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008636,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009698,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008094,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007109,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006090,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008642,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007113,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005623,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009435,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005375,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008114,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006098,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008649,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006694,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008294,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008127,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006101,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005241,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005634,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006328,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009836,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006952,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006711,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006120,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006527,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009122,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008474,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008300,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006533,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007727,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007955,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005653,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009301,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007958,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007523,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005661,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007734,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009960,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005667,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006131,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007129,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009306,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007739,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005906,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006353,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008488,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006363,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007349,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007355,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009969,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009853,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006746,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009318,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008681,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006372,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008165,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009975,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008497,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008496,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006552,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007762,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006985,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009740,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006987,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007763,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009613,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009327,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009616,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008871,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008873,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007765,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008877,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006562,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007980,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005442,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008331,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009474,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007371,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008519,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005449,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008894,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005705,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009331,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009478,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006777,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007169,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008903,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008905,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007390,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006188,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008907,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008526,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007993,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008529,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005718,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007173,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009200,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008914,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008541,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009998,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007999,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005484,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006400,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2010003,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007593,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008922,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006796,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005729,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005728,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008925,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008546,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009206,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009205,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005499,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006798,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007406,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008725,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007602,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2010018,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009212,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007189,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007416,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006231,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005519,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008201,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008202,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008199,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006596,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006598,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005751,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009646,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005754,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009886,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009892,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008013,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2010021,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006425,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007822,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008381,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008217,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006842,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008026,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008968,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008223,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2005552,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008036,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007222,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006265,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006442,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008400,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009773,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009225,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007635,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009226,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2010036,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006615,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007855,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2007068,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008589,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2009911,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006030,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006629,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2008999,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}",
//				"{\"processinstanceid\":2006037,\"data\":{\"result\":\"1\"},\"taskName\":\"EDI报价\",\"userid\":\"admin\"}"
//		};
		
		String[] a ={"{\"processinstanceid\":2008433,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009408,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007084,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009248,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006664,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005848,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006495,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009694,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007489,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008124,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006114,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006524,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005243,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007334,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009447,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009446,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009445,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006346,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008844,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008846,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005904,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007741,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008483,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006354,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008485,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007749,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009143,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006744,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008494,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005684,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006147,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009974,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005427,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009614,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005944,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2004821,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009479,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009484,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008344,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008347,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009487,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005485,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007402,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009495,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007415,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005746,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009364,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006420,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006421,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009884,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006240,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008014,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009764,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008384,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007214,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006840,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2006841,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2004072,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007449,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2008041,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2007646,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2005564,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}",
				"{\"processinstanceid\":2009914,\"data\":{\"result\":\"1\"},\"taskName\":\"精灵报价\",\"userid\":\"admin\"}"};
		
		for (int i = 0; i < a.length; i++) {
			params.put("datas",a[i]);
			  String result = HttpClientUtil.doGet("http://115.159.235.14:9080/workflow//process/completeSubTask",params);
		}
		
	
		
		 
		
		System.out.println(ValidateUtil.getConfigValue("core.url"));
		
//		String relt =HttpClientUtil.doPostJsonString("http://219.131.188.32:9080/cbs/ZHBCarCont/ZHBDockDeal", "{\"processinstanceid\":385151}");
//		String relt =HttpClientUtil.doPost("http://219.131.188.60:9081/cbs/ZHBCarCont/ZHBDockDeal", null, "UTF-8");

//		System.out.println(relt);
	}
}
