drop table if exists insecar;

CREATE TABLE `insecar` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `operator` varchar(20) NOT NULL COMMENT '操作员',
  `createtime` datetime NOT NULL COMMENT '创建时间',
  `modifytime` datetime DEFAULT NULL COMMENT '修改时间',
  `noti` text COMMENT '备注',
  `taskid` varchar(32) DEFAULT NULL COMMENT '任务id',
  `selectconfig` varchar(255) DEFAULT NULL COMMENT '已选择保险配置',
  `selectins` varchar(255) DEFAULT NULL COMMENT '已选择保险公司',
  `owner` varchar(32) DEFAULT NULL COMMENT '车主id',
  `ownername` varchar(30) DEFAULT NULL COMMENT '车主姓名',
  `phonenumber` int(11) DEFAULT NULL COMMENT '联系方式',
  `address` varchar(100) DEFAULT NULL COMMENT '联系地址',
  `carlicenseno` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `vincode` varchar(32) DEFAULT NULL COMMENT '车辆识别代号',
  `standardfullname` varchar(200) DEFAULT NULL COMMENT '车型信息描述',
  `engineno` varchar(50) DEFAULT NULL,
  `registdate` datetime DEFAULT NULL COMMENT '车辆初始登记日期',
  `registlicense` varchar(30) DEFAULT NULL COMMENT '注册许可证',
  `transferdate` datetime DEFAULT NULL COMMENT '过户日期',
  `isTransfercar` varchar(1) DEFAULT NULL COMMENT '过户车',
  `Specifydriver` varchar(32) DEFAULT NULL COMMENT '是否指定驾驶人',
  `drivingarea` varchar(30) DEFAULT NULL COMMENT '行驶区域',
  `mileage` varchar(50) DEFAULT NULL COMMENT '平均行驶里程',
  `accidentnum` int(11) DEFAULT NULL COMMENT '事故次数',
  `carid` int(11) DEFAULT NULL COMMENT '车辆编号',
  `useyears` int(11) DEFAULT NULL COMMENT '使用年限',
  `signdate` datetime DEFAULT NULL COMMENT '签署时间',
  `parksite` varchar(200) DEFAULT NULL COMMENT '固定停放地点',
  `preinscode` varchar(60) DEFAULT NULL COMMENT '上年商业承保公司',
  `taskstatus` varchar(30) DEFAULT NULL COMMENT '任务状态',
  `property` varchar(10) DEFAULT NULL COMMENT '所属性质',
  `carproperty` varchar(10) DEFAULT NULL COMMENT '车辆性质',
  `businessstartdate` datetime DEFAULT NULL COMMENT '起保日期',
  `businessenddate` datetime DEFAULT NULL COMMENT '终止日期',
  `Strongstartdate` datetime DEFAULT NULL,
  `Strongenddate` datetime DEFAULT NULL,
  `cloudinscompany` varchar(60) DEFAULT NULL,
  `isLicense` varchar(2) DEFAULT NULL COMMENT '车辆是否上牌，0未上牌/1已上牌',
  `inscomcode` varchar(50) DEFAULT NULL COMMENT '保险公司代码',
  `platecolor` int(11) DEFAULT NULL COMMENT '号牌颜色',
  `plateType` int(11) DEFAULT NULL COMMENT '号牌种类',
  `ineffectualDate` datetime DEFAULT NULL COMMENT '检验有效日期',
  `rejectDate` datetime DEFAULT NULL COMMENT '强制有效期',
  `lastCheckDate` datetime DEFAULT NULL COMMENT '最近定检日期',
  `isLoansCar` varchar(1) DEFAULT NULL COMMENT '上否贷款车',
  `carVehicularApplications` int(11) DEFAULT NULL COMMENT '车辆用途',
  `isFieldCar` varchar(1) DEFAULT NULL COMMENT '是否军牌外地车',
  `carBodyColor` int(11) DEFAULT NULL COMMENT '车身颜色',
  `loanManyYearsFlag` varchar(1) DEFAULT NULL COMMENT '上否车贷投保多年标志',
  `isNew` varchar(1) DEFAULT NULL COMMENT '新车标致，0 旧车/1 新车',
  `depprice` double DEFAULT NULL COMMENT '车辆折旧价',
  `floatprice` double DEFAULT NULL COMMENT '车辆浮动价',
  `isdanger` varchar(1) DEFAULT NULL COMMENT '是高危限制车型 0不是  1是',
  `isrob` varchar(1) DEFAULT NULL COMMENT '是易盗车型 0不是 1 是',
  `isspecial` varchar(1) DEFAULT NULL COMMENT '是管控车型 0不是 1 是',
  `maxprice` double DEFAULT NULL COMMENT '车辆浮动价上限',
  `maxpricerate` double DEFAULT NULL COMMENT '车辆浮动价上限比率',
  `minprice` double DEFAULT NULL COMMENT '车辆浮动价下限',
  `minpricerate` double DEFAULT NULL COMMENT '车辆浮动价下限比率',
  `taxprice` double DEFAULT NULL COMMENT '新车购置价',
  `drivinglicenseurl` varchar(150) DEFAULT NULL COMMENT '行驶证图片路径',
  `brandimg` varchar(200) DEFAULT NULL COMMENT '车辆照片（平台提供）',
  `cifstandardname` varchar(100) DEFAULT NULL COMMENT '平台查询传过来的车辆品牌',
  `insureconfigsameaslastyear` varchar(2) DEFAULT NULL COMMENT '保险配置是否与上年一致(1:是)',
  PRIMARY KEY (`id`),
  KEY `carinfohisTaskidIndex` (`taskid`) USING BTREE,
  KEY `carinfohisComcodeIndex` (`inscomcode`) USING BTREE,
  KEY `carinfohis_taskid` (`taskid`),
  KEY `idx_insbcarinfohis_carlicenseno` (`carlicenseno`),
  KEY `idx_insbcarinfohis_ownername` (`ownername`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
