USE `zzb_pro`;
DROP TABLE IF EXISTS `insbpersonHis`;
CREATE TABLE `insbpersonHis` (
  `id` VARCHAR(32) NOT NULL COMMENT '主键',
  `operator` VARCHAR(20) NOT NULL COMMENT '操作员',
  `createtime` DATETIME NOT NULL COMMENT '创建日期',
  `modifytime` DATETIME DEFAULT NULL COMMENT '修改日期',
  `optDate` DATETIME NOT NULL COMMENT '备份日期',
  `noti` VARCHAR(100) DEFAULT NULL COMMENT '备注',
  `taskid` VARCHAR(32) NOT NULL COMMENT '任务id',
  `name` VARCHAR(50) DEFAULT NULL COMMENT '姓名',
  `ename` VARCHAR(100) DEFAULT NULL COMMENT '英文名',
  `gender` INT(11) NOT NULL COMMENT '性别',
  `birthday` DATETIME DEFAULT NULL COMMENT '生日',
  `bloodtype` INT(11) DEFAULT NULL COMMENT '血型',
  `age` INT(11) DEFAULT NULL,
  `idcardtype` INT(11) DEFAULT NULL COMMENT '证件类型',
  `idcardno` VARCHAR(20) DEFAULT NULL COMMENT '证件号码',
  `cellphone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(50) DEFAULT NULL COMMENT '邮箱',
  `province` INT(11) DEFAULT NULL COMMENT '省',
  `city` INT(11) DEFAULT NULL COMMENT '城',
  `area` INT(11) DEFAULT NULL COMMENT '区县',
  `address` VARCHAR(100) DEFAULT NULL COMMENT '地址',
  `eaddress` VARCHAR(100) DEFAULT NULL,
  `zip` VARCHAR(10) DEFAULT NULL COMMENT '邮编',
  `licensetype` VARCHAR(20) DEFAULT NULL COMMENT '驾驶证类型',
  `licenseno` VARCHAR(50) DEFAULT NULL COMMENT '驾驶证号码',
  `licensedate` DATETIME DEFAULT NULL COMMENT '驾驶证发照日期',
  `maritalstatus` VARCHAR(10) DEFAULT NULL,
  `job` VARCHAR(30) DEFAULT NULL,
  `educateinfo` VARCHAR(50) DEFAULT NULL,
  KEY `idx_insbPersonHis_taskid` (`taskid`),
  KEY `idx_insbpersonHis_idcardno` (`idcardno`),
  KEY `idx_insbpersonHis_name` (`name`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
